import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { X, ExternalLink, Github, AlertCircle, CheckCircle2, Cpu, Calendar, Share2, Check } from 'lucide-react';
import { Project, ThemeAccent, Language } from '../types';
import { PROJECT_TRANSLATIONS } from '../data/projectTranslations';

interface ModalProps { project: Project | null; onClose: () => void; accent: ThemeAccent; lang: Language; }

export const ProjectDetailModal: React.FC<ModalProps> = ({ project, onClose, lang }) => {
  const [copiedLink, setCopiedLink] = useState(false);
  if (!project) return null;
  const id = lang === 'id';
  const translation = id ? PROJECT_TRANSLATIONS[project.id] : undefined;
  const summary = translation?.summary || project.summary[lang];
  const description = translation?.description || project.description[lang];
  const overview = translation?.overview || project.architecture?.overview[lang];
  const challenges = translation?.challenges || project.architecture?.challenges[lang];
  const solutions = translation?.solutions || project.architecture?.solutions[lang];
  const handleShare = () => { if (navigator.clipboard) { navigator.clipboard.writeText(`${window.location.origin}#project-${project.id}`); setCopiedLink(true); setTimeout(()=>setCopiedLink(false),2000); } };
  const isTs=project.techBadge==='TS', isJs=project.techBadge==='JS';
  return <AnimatePresence><div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md" onClick={onClose}><motion.div initial={{opacity:0,scale:.95,y:20}} animate={{opacity:1,scale:1,y:0}} exit={{opacity:0,scale:.95,y:20}} transition={{duration:.25}} onClick={e=>e.stopPropagation()} className="relative w-full max-w-xl max-h-[85vh] rounded-2xl bg-[#16171e] border border-white/10 shadow-2xl flex flex-col overflow-hidden text-zinc-100">
    <div className="flex items-center justify-between px-5 py-4 border-b border-white/10 bg-[#13141a]"><div className="flex items-center gap-2 text-xs font-mono text-zinc-400"><span className="px-2 py-0.5 rounded bg-white/[0.08] text-white font-medium">{project.typeBadge||'PROJECT'}</span><span>•</span><span className="flex items-center gap-1"><Calendar className="w-3.5 h-3.5"/>{project.year}</span></div><div className="flex items-center gap-2"><button type="button" onClick={handleShare} className="p-1.5 rounded-lg text-zinc-400 hover:text-white hover:bg-white/5 cursor-pointer">{copiedLink?<Check className="w-4 h-4 text-emerald-400"/>:<Share2 className="w-4 h-4"/>}</button><button type="button" onClick={onClose} className="p-1.5 rounded-lg text-zinc-400 hover:text-white hover:bg-white/5 cursor-pointer" aria-label={id?'Tutup':'Close'}><X className="w-5 h-5"/></button></div></div>
    <div className="flex-1 overflow-y-auto p-5 sm:p-6 space-y-5 text-sm leading-relaxed text-zinc-300 font-sans"><div className="flex items-start gap-3.5"><div className={`w-10 h-10 rounded-xl flex items-center justify-center font-bold text-sm shadow-md shrink-0 ${isTs?'bg-[#007acc] text-white font-mono':isJs?'bg-[#f7df1e] text-zinc-950 font-mono':'bg-zinc-800 text-zinc-200 font-mono'}`}>{project.techBadge||'DEV'}</div><div><h2 className="text-xl sm:text-2xl font-bold text-white tracking-tight">{project.title}</h2><p className="text-xs text-zinc-400 font-mono">{project.categoryLabel[lang]}</p></div></div>
      <div className="text-xs text-zinc-300 bg-white/[0.04] p-3.5 rounded-xl border border-white/5 leading-relaxed">{summary}</div><div className="space-y-1.5 text-xs sm:text-sm text-zinc-300 leading-relaxed"><p>{description}</p></div>
      {project.metrics?.length>0&&<div className="grid grid-cols-2 gap-2.5 pt-1">{project.metrics.map((m,i)=><div key={i} className="p-3 rounded-xl bg-[#1a1b24] border border-white/5 text-xs"><span className="text-zinc-500 block text-[11px] font-mono uppercase mb-0.5">{m.label[lang]}</span><span className="font-bold text-white text-sm font-mono">{m.value}</span></div>)}</div>}
      {project.architecture&&<div className="p-4 rounded-xl bg-[#1a1b24] border border-white/5 space-y-3"><div className="flex items-center gap-2 text-xs font-semibold text-white font-mono uppercase tracking-wider"><Cpu className="w-3.5 h-3.5 text-cyan-400"/>{id?'Arsitektur & Spesifikasi':'Architecture & Specs'}</div><p className="text-zinc-300 leading-relaxed text-xs">{overview}</p><div className="grid grid-cols-1 gap-2"><div className="p-2.5 rounded-lg bg-[#14151c] border border-white/5"><div className="flex items-center gap-1.5 text-amber-400 font-mono text-[11px]"><AlertCircle className="w-3.5 h-3.5"/>{id?'Tantangan':'Challenge'}</div><p className="text-zinc-400 text-[11px] leading-relaxed mt-1">{challenges}</p></div><div className="p-2.5 rounded-lg bg-[#14151c] border border-white/5"><div className="flex items-center gap-1.5 text-emerald-400 font-mono text-[11px]"><CheckCircle2 className="w-3.5 h-3.5"/>{id?'Solusi':'Solution'}</div><p className="text-zinc-400 text-[11px] leading-relaxed mt-1">{solutions}</p></div></div></div>}
      <div className="space-y-2"><span className="text-[11px] font-mono text-zinc-500 uppercase tracking-wider block">{id?'Teknologi Terpasang':'Technologies & Modules'}</span><div className="flex flex-wrap gap-1.5">{project.tags.map((tag,i)=><span key={i} className="px-2.5 py-1 rounded-lg bg-white/[0.05] border border-white/5 text-[11px] font-mono text-zinc-300">{tag}</span>)}</div></div>
    </div><div className="px-5 py-3 border-t border-white/10 bg-[#13141a] flex items-center justify-between gap-2"><div className="flex items-center gap-2">{project.liveUrl&&<a href={project.liveUrl} target="_blank" rel="noopener noreferrer" className="flex items-center gap-1.5 px-3.5 py-1.5 rounded-xl bg-white text-zinc-950 text-xs font-semibold cursor-pointer"><ExternalLink className="w-3.5 h-3.5"/>{id?'Demo':'Demo'}</a>}{project.githubUrl&&<a href={project.githubUrl} target="_blank" rel="noopener noreferrer" className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-white/[0.08] text-zinc-200 text-xs font-medium border border-white/10 cursor-pointer"><Github className="w-3.5 h-3.5"/>GitHub</a>}</div><button type="button" onClick={onClose} className="px-4 py-1.5 rounded-xl bg-white/[0.08] text-zinc-300 text-xs font-medium border border-white/10 cursor-pointer">{id?'Tutup':'Close'}</button></div>
  </motion.div></div></AnimatePresence>;
};
